// Generated by: npm run gen:types (supabase gen types typescript --local)
// DO NOT EDIT MANUALLY — regenerate after schema changes

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      app_settings: {
        Row: { key: string; value: string }
        Insert: { key: string; value: string }
        Update: { key?: string; value?: string }
        Relationships: []
      }
      audit_logs: {
        Row: {
          action: string; id: string; new_data: Json | null; old_data: Json | null
          performed_at: string; performed_by: string | null; record_id: string; table_name: string
        }
        Insert: {
          action: string; id?: string; new_data?: Json | null; old_data?: Json | null
          performed_at?: string; performed_by?: string | null; record_id: string; table_name: string
        }
        Update: {
          action?: string; id?: string; new_data?: Json | null; old_data?: Json | null
          performed_at?: string; performed_by?: string | null; record_id?: string; table_name?: string
        }
        Relationships: []
      }
      awards: {
        Row: { award_value: string; category: string; description: string; id: string; recipient_count: number; title: string; year: number }
        Insert: { award_value?: string; category: string; description: string; id?: string; recipient_count?: number; title: string; year?: number }
        Update: { award_value?: string; category?: string; description?: string; id?: string; recipient_count?: number; title?: string; year?: number }
        Relationships: []
      }
      hashtags: {
        Row: { id: string; name: string }
        Insert: { id?: string; name: string }
        Update: { id?: string; name?: string }
        Relationships: []
      }
      kudos: {
        Row: { content: string; created_at: string; id: string; is_anonymous: boolean; receiver_id: string; sender_id: string | null }
        Insert: { content: string; created_at?: string; id?: string; is_anonymous?: boolean; receiver_id: string; sender_id?: string | null }
        Update: { content?: string; created_at?: string; id?: string; is_anonymous?: boolean; receiver_id?: string; sender_id?: string | null }
        Relationships: [
          { foreignKeyName: "kudos_receiver_id_fkey"; columns: ["receiver_id"]; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "kudos_sender_id_fkey"; columns: ["sender_id"]; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      kudos_hashtags: {
        Row: { hashtag_id: string; kudos_id: string }
        Insert: { hashtag_id: string; kudos_id: string }
        Update: { hashtag_id?: string; kudos_id?: string }
        Relationships: [
          { foreignKeyName: "kudos_hashtags_hashtag_id_fkey"; columns: ["hashtag_id"]; referencedRelation: "hashtags"; referencedColumns: ["id"] },
          { foreignKeyName: "kudos_hashtags_kudos_id_fkey"; columns: ["kudos_id"]; referencedRelation: "kudos"; referencedColumns: ["id"] },
        ]
      }
      kudos_images: {
        Row: { id: string; kudos_id: string; order_index: number; url: string }
        Insert: { id?: string; kudos_id: string; order_index?: number; url: string }
        Update: { id?: string; kudos_id?: string; order_index?: number; url?: string }
        Relationships: [
          { foreignKeyName: "kudos_images_kudos_id_fkey"; columns: ["kudos_id"]; referencedRelation: "kudos"; referencedColumns: ["id"] },
        ]
      }
      nomination_periods: {
        Row: { created_at: string; end_at: string; id: string; start_at: string; year: number }
        Insert: { created_at?: string; end_at: string; id?: string; start_at: string; year: number }
        Update: { created_at?: string; end_at?: string; id?: string; start_at?: string; year?: number }
        Relationships: []
      }
      nominations: {
        Row: { award_id: string; created_at: string; id: string; nominator_id: string; nominee_id: string; period_id: string; reason: string | null }
        Insert: { award_id: string; created_at?: string; id?: string; nominator_id: string; nominee_id: string; period_id: string; reason?: string | null }
        Update: { award_id?: string; created_at?: string; id?: string; nominator_id?: string; nominee_id?: string; period_id?: string; reason?: string | null }
        Relationships: [
          { foreignKeyName: "nominations_award_id_fkey"; columns: ["award_id"]; referencedRelation: "awards"; referencedColumns: ["id"] },
          { foreignKeyName: "nominations_nominator_id_fkey"; columns: ["nominator_id"]; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "nominations_nominee_id_fkey"; columns: ["nominee_id"]; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "nominations_period_id_fkey"; columns: ["period_id"]; referencedRelation: "nomination_periods"; referencedColumns: ["id"] },
        ]
      }
      profiles: {
        Row: { avatar_url: string | null; created_at: string; full_name: string; hero_level: string; id: string; role: string; updated_at: string }
        Insert: { avatar_url?: string | null; created_at?: string; full_name: string; hero_level?: string; id: string; role?: string; updated_at?: string }
        Update: { avatar_url?: string | null; created_at?: string; full_name?: string; hero_level?: string; id?: string; role?: string; updated_at?: string }
        Relationships: []
      }
    }
    Views: {
      nominations_count_by_award: {
        Row: { award_id: string | null; nomination_count: number | null; period_id: string | null }
        Relationships: [
          { foreignKeyName: "nominations_award_id_fkey"; columns: ["award_id"]; referencedRelation: "awards"; referencedColumns: ["id"] },
          { foreignKeyName: "nominations_period_id_fkey"; columns: ["period_id"]; referencedRelation: "nomination_periods"; referencedColumns: ["id"] },
        ]
      }
    }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  T extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"]),
> = (DefaultSchema["Tables"] & DefaultSchema["Views"])[T] extends { Row: infer R } ? R : never

export type TablesInsert<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T] extends { Insert: infer I } ? I : never

export type TablesUpdate<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T] extends { Update: infer U } ? U : never

export const Constants = {
  public: { Enums: {} },
} as const
